In [1]:
from collections import defaultdict, Counter
from typing import List, Set, Tuple
# from scipy.spatial.distance import cityblock as manhattan_dist # this is SLOW AF

In [2]:
with open('data.txt') as datafile:
    data = datafile.read().split('\n')

In [3]:
test_case = [
    '1, 1',
    '1, 6',
    '8, 3',
    '3, 4',
    '5, 5',
    '8, 9',
]

In [4]:
def convert_text_to_coordiates(coord_text):
    '''
    convert list of something like "1, 1" to set of (1, 1)
    
    return: 
    set of tupule x, y points
    max x
    max y
    '''
    coords = set()
    max_x, max_y = 0, 0
    for text in coord_text:
        x, y = map(int, text.split(','))
        coords.add((x, y))
        if x > max_x: max_x = x
        if y > max_y: max_y = y
    return {'coordinates': coords, 'max_x': max_x, 'max_y': max_y}

In [5]:
def manhattan_dist(p1: Tuple[int, int], p2: Tuple[int, int]) -> int:
    x1, y1 = p1
    x2, y2 = p2
    return abs(x2 - x1) + abs(y2 - y1)

In [210]:
def find_closest_points(point: tuple, coordinates: set) -> list :
    points = []
    min_dist = 99999999
    for coord in coordinates:
        pt_dist = manhattan_dist(point, coord)
        # add tied min distance points
        if pt_dist == min_dist:
            min_dist = pt_dist
            points.append(coord)
        # new min distance
        if pt_dist < min_dist:
            min_dist = pt_dist
            points.clear()
            points.append(coord)
    if len(points) == 1:
        point = points[0]
        return point
    return None

In [146]:
def define_edges(max_x: int, max_y: int):
    bottom_edge = [(x, 0) for x in range(max_x+1)]
    top_edge = [(x, max_y) for x in range(max_x+1)]
    left_edge = [(0, y) for y in range(max_y+1)]
    right_edge = [(max_x, y) for y in range(max_y+1)]
    edges = bottom_edge + top_edge + left_edge + right_edge
    return set(edges)

In [211]:
def count_areas(coordinates):
    coords = coordinates.get('coordinates')
    max_x = coordinates.get('max_x')
    max_y = coordinates.get('max_y')
    area_counts = defaultdict(float)
    edges = define_edges(max_x, max_y)
    for x in range(max_x+1):
        for y in range(max_y+1):
            closest_point = (find_closest_points((x, y), coords))
            if (x, y) in edges:
                area_counts[closest_point] += float('inf')
            else:
                area_counts[closest_point] += 1
    return area_counts

In [212]:
def part_one_answer(raw_data):
    coords = convert_text_to_coordiates(raw_data)
    area_counts = count_areas(coords)
    max_area = max([a for a in area_counts.values() if a != float('inf')])
    return {'area_counts': area_counts, 'max_area': max_area}

In [221]:
part_one_answer(test_case)

{'area_counts': defaultdict(float,
             {(1, 1): inf,
              None: inf,
              (1, 6): inf,
              (3, 4): 9.0,
              (5, 5): 17.0,
              (8, 9): inf,
              (8, 3): inf}),
 'max_area': 17.0}

In [222]:
%time part_one_answer(data)

CPU times: user 5.78 s, sys: 5 ms, total: 5.78 s
Wall time: 5.89 s


{'area_counts': defaultdict(float,
             {(132, 74): inf,
              (99, 112): inf,
              (60, 188): inf,
              None: inf,
              (43, 223): inf,
              (40, 321): inf,
              (58, 334): inf,
              (84, 243): 1788.0,
              (85, 305): 1864.0,
              (86, 343): inf,
              (92, 185): 1436.0,
              (97, 254): 424.0,
              (109, 228): 1473.0,
              (110, 292): 2491.0,
              (106, 199): 552.0,
              (102, 257): 1439.0,
              (134, 144): 1692.0,
              (140, 168): 335.0,
              (125, 199): 1016.0,
              (153, 188): 933.0,
              (158, 95): 2395.0,
              (176, 307): inf,
              (141, 167): 330.0,
              (174, 212): 1760.0,
              (172, 131): 1501.0,
              (201, 50): inf,
              (182, 151): 1259.0,
              (189, 188): 1356.0,
              (183, 205): 242.0,
              (219, 266): 2906.0,


In [217]:
def part_two_answer(raw_data, min_dist):
    coordinates = convert_text_to_coordiates(raw_data)
    coords = coordinates.get('coordinates')
    max_x = coordinates.get('max_x')
    max_y = coordinates.get('max_y')
    keep = set()
    for x in range(max_x+1):
        for y in range(max_y+1):
            point_dist = []
            for c in coords:
                point_dist.append(manhattan_dist((x, y), c))
            if sum(point_dist) < min_dist:
                keep.add((x, y))
    return len(keep)

In [218]:
part_two_answer(test_case, 32)

16

In [220]:
%time part_two_answer(data, 10000)

CPU times: user 6.28 s, sys: 9 ms, total: 6.29 s
Wall time: 6.56 s


50530

In [6]:
from scipy.spatial.distance import cityblock
import numpy as np

In [7]:
data_coords = convert_text_to_coordiates(data)
coords = data_coords.get('coordinates')
max_x = data_coords.get('max_x')
max_y = data_coords.get('max_y')

In [8]:
data_array = np.array([[int(text.split(',')[0]), int(text.split(',')[1])] for text in data])

In [9]:
data_array[:, 0], data_array[1]

(array([227, 140,  99, 318, 219, 134, 306, 189,  58, 337, 255, 245, 102,
        255, 303, 141,  40, 201,  60, 132, 125, 176, 204, 338, 276, 292,
        109,  85,  86,  97, 182, 110, 285,  43, 153, 285, 334,  84,  92,
        330, 259, 106, 183, 188, 231, 158, 174, 279, 172, 247]),
 array([140, 168]))

In [10]:
grid = np.array([[x, y] for x in range(max_x+1) for y in range(max_y+1)])

In [11]:
from scipy.spatial.distance import cdist

dists = cdist(grid, data_array, 'cityblock')

In [12]:
%time cdist(grid, data_array, 'cityblock')

CPU times: user 49 ms, sys: 40 ms, total: 89 ms
Wall time: 200 ms


array([[360., 308., 211., ..., 376., 303., 567.],
       [359., 307., 210., ..., 375., 302., 566.],
       [358., 306., 209., ..., 374., 301., 565.],
       ...,
       [329., 381., 478., ..., 313., 386., 122.],
       [330., 382., 479., ..., 314., 387., 123.],
       [331., 383., 480., ..., 315., 388., 124.]])

In [13]:
closest_points = dists.argmin(axis=1)

In [14]:
def define_edges_np(data: np.array):
    max_x, max_y = data.max(axis=0)
    bottom_edge = [[x, 0] for x in range(max_x+1)]
    top_edge = [[x, max_y] for x in range(max_x+1)]
    left_edge = [[0, y] for y in range(max_y+1)]
    right_edge = [[max_x, y] for y in range(max_y+1)]
    edges = bottom_edge + top_edge + left_edge + right_edge
    return np.array(edges)

In [15]:
edges = define_edges_np(grid)

In [351]:
keep = np.isin(grid, define_edges_np(grid))

In [19]:
keep = [row for row in grid if row in edges]

In [31]:
np.isin(grid[20], edges[0])

array([ True, False])

In [297]:
Counter(closest_points).most_common()

[(19, 12753),
 (2, 7071),
 (17, 6225),
 (10, 5799),
 (18, 5385),
 (21, 5137),
 (3, 4480),
 (33, 4314),
 (16, 4236),
 (4, 2972),
 (6, 2890),
 (49, 2666),
 (31, 2491),
 (45, 2449),
 (14, 2433),
 (35, 2310),
 (22, 2302),
 (11, 2238),
 (25, 1993),
 (28, 1946),
 (0, 1927),
 (27, 1908),
 (38, 1807),
 (37, 1799),
 (46, 1760),
 (5, 1708),
 (40, 1649),
 (13, 1643),
 (12, 1537),
 (26, 1524),
 (24, 1520),
 (48, 1501),
 (7, 1441),
 (44, 1338),
 (47, 1334),
 (23, 1328),
 (36, 1323),
 (30, 1321),
 (39, 1288),
 (9, 1132),
 (32, 1050),
 (8, 1040),
 (20, 1027),
 (34, 933),
 (1, 865),
 (43, 592),
 (41, 552),
 (29, 462),
 (15, 330),
 (42, 277)]