--- Day 21: Fractal Art ---

In [112]:
starting_pattern = ".#./..#/###"

In [7]:
rules = readLines("input.txt")

Warning message in readLines("input.txt"):
“incomplete final line found on 'input.txt'”


In [9]:
length(rules)

[1] 108

In [11]:
tail(rules, 1)

[1] "###/###/### => .##./##../..#./.###"

In [67]:
rule_df = data.frame(text = rules, stringsAsFactors = FALSE)

In [68]:
rule_df$rule = str_split(rule_df$text, " => ")

In [70]:
rule_df$input = sapply(rule_df$rule, function(x) x[1])

In [72]:
rule_df$output = sapply(rule_df$rule, function(x) x[2])

In [73]:
head(rule_df)

text                 rule                     input output     
1 ../.. => .#./###/##. ../..      , .#./###/##. ../.. .#./###/##.
2 #./.. => ..#/.#./#.# #./..      , ..#/.#./#.# #./.. ..#/.#./#.#
3 ##/.. => ###/#../... ##/..      , ###/#../... ##/.. ###/#../...
4 .#/#. => .#./..#/##. .#/#.      , .#./..#/##. .#/#. .#./..#/##.
5 ##/#. => ..#/#.#/### ##/#.      , ..#/#.#/### ##/#. ..#/#.#/###
6 ##/## => .##/.##/.#. ##/##      , .##/.##/.#. ##/## .##/.##/.#.

In [114]:
pattern_as_matrix = function(pattern) {
    chars = unlist(strsplit(gsub("/", "", pattern), ""))
    l = length(chars)
    if (l %% 2 == 0) {
        d = 2
    } else {
        d = 3
    }
    return(structure(chars, .Dim = c(d, d)))
}

In [115]:
rotate <- function(x) t(apply(x, 2, rev))

In [116]:
sp = pattern_as_matrix(starting_pattern)

In [117]:
sp

[,1] [,2] [,3]
[1,] .    .    #   
[2,] #    .    #   
[3,] .    #    #

In [118]:
t(sp)

[,1] [,2] [,3]
[1,] .    #    .   
[2,] .    .    #   
[3,] #    #    #

In [119]:
rotate(sp)

[,1] [,2] [,3]
[1,] .    #    .   
[2,] #    .    .   
[3,] #    #    #

In [138]:
matrix_to_pattern = function(mat) paste(as.character(mat), collapse = "")

In [145]:
matrix_to_pattern(sp) %in% rule_df$input

[1] FALSE

In [160]:
check_for_matching_matrix <- function(mat) {
    not_done = TRUE
    attempts = 1
    while (not_done) {
        if (attempts %% 4 == 0) {
            mat = t(mat)
        } else {
            mat = rotate(mat)
        }
        if (matrix_to_pattern(mat) %in% rule_df$input) {
            return(mat)
        }
    }
}

In [161]:
check_for_matching_matrix(sp)

In [153]:
matrix_to_pattern(t(rotate(rotate(rotate(sp))))) %in% rule_df$input

[1] FALSE